config/routes.rb
Bluebook::Application.routes.draw do
  devise_for :users

  
  match 'clients/new' => 'clients#new', :via => :get
  match 'clients/create' => "clients#create", :via => :post, :as => "clients"
  match 'invoice/new' => 'invoice#new', :via => :get
  match 'invoice/create' => "invoice#create", :via => :post, :as => "invoices"
  match 'invoice/index' => 'invoice#index', :via => :get
  match 'invoice/edit' => 'invoice#edit'
  match 'invoice/generate' => 'invoice#generate'
  match 'invoice/delete' => 'invoice#delete', :via => :delete

  root :to => "clients#new"
end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :line_1, :city, :state, :pincode, :primary_email, :secondary_email, :mobile_number, :alternate_number
#  validates_presence_of :line_1, :city, :state, :pincode
  belongs_to :customer
  belongs_to :client
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name, :address_attributes
#  validate_presence_of :name
  belongs_to :user
  has_many :invoices
  has_one :address
  accepts_nested_attributes_for :address
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :name, :address_attributes
  
#  validate_presence_of :name
  has_one :address
  accepts_nested_attributes_for :address
  belongs_to :invoice
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :tax, :grand_total, :date, :client_id, :status_id, :customer_attributes, :products_attributes
  
  has_one :customer
  accepts_nested_attributes_for :customer
  has_many :products
  accepts_nested_attributes_for :products

  has_one :status
  belongs_to :client  
#  validates_presence_of :tax, :grand_total, :date
  
end

app/models/invoice_client.rb
class InvoiceClient < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :invoice
  belongs_to :client
  
end

app/models/invoice_product.rb
class InvoiceProduct < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :invoice
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :item, :price, :quantity, :description
  belongs_to :invoice
  validates_presence_of :item, :price, :quantity
end

app/models/status.rb
class Status < ActiveRecord::Base
  # attr_accessible :title, :body
  validates_presence_of :code, :name
  
  attr_accessible :code, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @client = Client.new
    @client.build_address
  end
  
  def create
    client = Client.create(params[:client])
    redirect_to clients_new_path, :notice => "Successfully created"
  end
end

app/controllers/invoice_controller.rb
class InvoiceController < ApplicationController

  def index
    @invoices = Invoice.all  
  end
  
  def new
    @invoice = Invoice.new
    @clients = Client.all
    customer = @invoice.build_customer
    customer.build_address
    @invoice.products.build
  end
  
  def create
    @invoice = Invoice.create(params[:invoice])
    redirect_to invoice_new_path, :notice => "Successfully created"
  end
  
  def edit
    @invoice = Invoice.find(params[:id])
  end
  
  def delete
    @invoice = Invoice.find(params[:id])
    @invoice.delete_all
  end
  
  def generate
    @invoice = Invoice.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
  def grand_total(invoice)
    sum = 0
    if invoice.products.present?
      invoice.products.each do |product|
        sum = sum + product.price * product.quantity
      end
    end
    return sum
  end
end

app/views/clients/new.html.erb
<h2>New Client</h2>
<%= form_for @client do |f| %>
<table>
	<tr><td>Name:</td>
		<td><%= f.text_field :name %></td>
	</tr>
	<%= f.fields_for :address do |addr_fields| %>
		<%= render :partial => '/partials/address_fields', :locals => { :f => addr_fields} %>
	<% end %>
	<tr>
		<td><%= f.submit :submit %></td>
	</tr>
</table>
<% end %>

app/views/invoice/_product_fields.html.erb
<p class="fields">
<%= f.fields_for :products do |product| %>
	<tr>
		<td>Item</td>
		<td><%= product.text_field :item %></td>
	</tr>
	<tr>
		<td>Description</td>
		<td><%= product.text_area :description, :rows => 3, :cols => 3 %></td>
	</tr>
	<tr>
		<td>Price</td>
		<td><%= product.text_field :price %></td>
	</tr>
	<tr>
		<td>Quantity</td>
		<td><%= product.text_field :quantity %></td>
	</tr>
<% end %>
</p>

app/views/invoice/generate.html.erb
<div class = "inv-container">
	<div class="inv-header clearfix">
		<div class="logo">
			<h1>Bluebook</h1>		
		</div>
		<div class="address">
			<%= @invoice.client.name %><br/>
			<%= @invoice.client.address.line_1 %><br/>
			<%= @invoice.client.address.city %><br/>
			<%= @invoice.client.address.state %>-<%= @invoice.client.address.pincode %>
		</div>
	</div>
	<div class="inv-main">
		<div class="inv-details">
			<div class="tot">	
				<b>Total:</br></b>
				<b class="g-tot"><%= grand_total(@invoice) %><br/></b>
			</div>
			<div class="bill">
				<b>Bill To:<br/></b>
				<%= @invoice.customer.name %><br/>
				<%= @invoice.customer.address.line_1 %><br/>
				<%= @invoice.customer.address.city %>,<%= @invoice.customer.address.state %>-<%= @invoice.customer.address.pincode %><br/>
			</div>
			<div class="inv-sub-details">
				Invoice#:<br/>
				<b><%= @invoice.id %><br/></b>
			
				Invoice Date:<br/>
				<b><%= @invoice.date %><br/></b>
			</div>
		</div>
		<!-- end of inv-details -->
		<div class="inv-prod">
			<table cellpadding="5" cellspacing="5" width="100%" border="0">
				<tr>
					<th width="60%">ITEMS</th>
					<th width="10%">PRICE</th>
					<th width="10%">QUANTITY</th>
					<th width="20%">AMOUNT</th>
				</tr>
				<% @invoice.products.each do |prod| %>
				<tr>
					<td><%= prod.item %></td>
					<td><%= prod.price %></td>
					<td><%= prod.quantity %></td>
					<td><%= prod.price * prod.quantity %></td>
				</tr>
				<% end %>
				<tr>
					<td>Item1</td>
					<td>1000</td>
					<td>2</td>
					<td>2000</td>
				</tr>
				<tr>
					<td>Item2</td>
					<td>1500</td>
					<td>2</td>
					<td>3000</td>
				</tr>
				<tr class="no-border">
					<td></td>
					<td></td>
					<td>Subtotal:</td>
					<td><%= grand_total(@invoice) %></td>
				</tr>
				<tr class="no-border">
					<td></td>
					<td></td>
					<td>Total:</td>
					<td>$<%= grand_total(@invoice) %></td>
				</tr>
				<tr class="no-border">
					<td></td>
					<td></td>
					<td>Payment Made:</td>
					<td>0.0</td>
				</tr>
				<tr class="no-border">
					<td></td>
					<td></td>
					<td>Balance Due:</td>
					<td>$<%= grand_total(@invoice) %></td>
				</tr>
			</table>
			<p>Thanks for your business</p>
		</div>
	</div>
</div>

app/views/invoice/index.html.erb
<table>
	<tr>
		<th>Customer Name</th>
		<th>Address</th>
		<th>Client</th>
		<th>Date</th>
		<th>Grand Total</th>
	</tr>
	<% @invoices.each do |invoice| %>
	<tr>
		<td><%= invoice.customer.name %></td>
		<td><%= invoice.customer.address.line_1 %></td>
		<td><%= invoice.try(:client).try(:name) %></td>
		<td><%= invoice.date %></td>
		<td><%= grand_total(invoice) %></td>
		<td><%= link_to 'Edit', invoice_edit_path(:id => invoice.id)%></td>
		<td><%= link_to 'Generate', invoice_generate_path(:id => invoice.id)%></td>
		<td><%= link_to 'Delete', invoice_delete_path(:id => invoice.id)%></td>
	</tr>
	<% end %>
</table>

app/views/invoice/new.html.erb
<h2>New Invoice</h2>
<%= form_for @invoice do |f| %>
  <table>
  	<tr>
  		<td>Client Name</td>
  		<td><%= f.select :client_id, options_from_collection_for_select(@clients, "id", "name")%></td>
	</tr>
	<tr>
		<td>Date</td>
		<td><%= f.text_field :date %></td>
	</tr>
    <%= f.fields_for :customer do |customer_fields| %>
	<tr>
		<td>Name</td>
		<td><%= customer_fields.text_field :name %></td>
	</tr>
	<%= customer_fields.fields_for :address do |addr_fields|%>
		<%= render :partial => '/partials/address_fields', :locals => {:f => addr_fields} %>
	<% end %>
	<% end %>
	
	<%= render 'product_fields', :f => f %>
	<p><%= link_to_add_fields "Add Product", f, :products %></p>	
	<tr>
		<td>Tax</td>
		<td><%= f.text_field :tax%></td>
	</tr>
	
	<tr>
		<td><%= f.submit :submit %></td>
	</tr>
</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="/assets/style.css" type="text/css" media='screen' />
  <title>Bluebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <a href=>
</head>
<body>
	<div class="navbar navbar-fixed-top navbar-inverse">
	  <div class="navbar-inner">
	    <a class="brand" href="#">Bluebook</a>
	    <ul class="nav">
	      <li class="active"><a href="#">Client</a></li>
	      <li><a href="<%= invoice_new_path %>">Link</a></li>
	      <li><a href="<%= invoice_index_path %>">Link2</a></li>
	    </ul>
	  </div>
	</div>
	<div class="container">
      <div class="row">
		<div class="span2"></div>
		<div class="span10"><%= yield %></div>
	  </div>
	</div>
	<% if notice.present? %>
      <p>
        <%= raw notice %>
      </p>
    <% end %>   
</body>
</html>

app/views/partials/_address_fields.html.erb
<p class="fields"></p>
<tr>
	<td>Address</td>
	<td><%= f.text_area :line_1, :rows => 3, :cols => 3 %></td>
</tr>
<tr>
	<td>City</td>
	<td><%= f.text_field :city %></td>
</tr>
<tr>
	<td>State</td>
	<td><%= f.text_field :state %></td>
</tr>
<tr>
	<td>Pincode</td>
	<td><%= f.text_field :pincode %></td>
</tr>
<tr>
	<td>Primary Email</td>
	<td><%= f.text_field :primary_email %></td>
</tr>
<tr>
	<td>Secondary Email</td>
	<td><%= f.text_field :secondary_email %></td>
</tr>
<tr>
	<td>Mobile Number</td>
	<td><%= f.text_field :mobile_number %></td>
</tr>
<tr>
	<td>Alternate Contact Number</td>
	<td><%= f.text_field :alternate_number %></td>
</tr>
</p>